### ISSUE TITLE
Error in table 6

### ISSUE THREAD

**Issue by developer0hye** [jozhang97/DETA#5]
![image](https://user-images.githubusercontent.com/35001605/209087529-3b90ee88-2777-4be2-b1b3-184b91643a60.png)

@jozhang97 
Thanks for sharing your work!

It seems that APs in the table 6. is so high. I think that the order of values in APL and APs should be changed.

**Comment by jozhang97** [comment]
Hi, oh my, you're right thank you for catching us!
Will be fixed in the next revision!

**Comment by jozhang97** [comment]
It turns out Table 6 currently reports AP,AP50,AP75,APs instead of AP,APs,APm,APl. Thanks again for catching this.

Revised table below.

| First | Second | AP   | APs  | APm  | APl  |
|-------|--------|------|------|------|------|
| 1     | 1      | 43.2 | 25.9 | 46.6 | 57.6 |
| 1     | 2      | 44.7 | 26.8 | 47.6 | 59.8 |
| 1     | 4      | 45.1 | 27.1 | 48.0 | 60.4 |
| 1     | 8      | 43.0 | 24.5 | 46.3 | 59.2 |
| 2     | 1      | 44.0 | 27.7 | 46.7 | 58.3 |
| 4     | 1      | 43.7 | 25.6 | 47.0 | 57.9 |
| 8     | 1      | 43.1 | 26.4 | 46.7 | 56.4 |
| 2     | 2      | 45.4 | **28.6** | **48.5** | 60.1 |
| 4     | 4      | **45.8** | 28.4 | 48.4 | **60.7** |

**Comment by developer0hye** [comment]
@jozhang97 Thanks again for sharing your work!
